### ISSUE TITLE
Allow linking directly to Manchester or London listings

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/the-trans-dimension#466]
## User story

As someone living in Manchester or London and wanting to send a link to a friend, I want to be able to send a URL that only contains London or Manchester listings, in order that people don't get confused which listings are which.

As someone plugging the Manchester expansion on social media, I want to be able to track clicks to Manchester listings specificallly, in order that I can judge the success of my campaign

## Acceptance criteria

- [ ] I can generate a link to just Manchester events
- [ ] I can generate a link to just Manchester partners
- [ ] If I press the back button it saves that I have selected Manchester

## Split this off so we could get live with progress so far

- [x] #470

## Implementation plan

<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRmMDgxZmQyZWY0Y2JjYzQ2ZGUxNGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.lP-1eh4GLVcw9df5I8d7ogkFikJt90SHKS393VBx2vA">Huly&reg;: <b>TD-467</b></a></sub>

**Comment by katjam** [comment]
@kimadactyl Would something like https://transdimension.uk/?filter=manchester be OK or did you have something else in mind?

We could rig up https://manchester.transdimension.uk etc...

**Comment by kimadactyl** [comment]
that works great. as long as you can link to it, and once set it stays persistant when you change pages, its all good

**Comment by katjam** [comment]
It won't persist between page navigations by default, but we can make it do that. Do we want the persistent filter in the url to also to be set when people click a region button on any of the 3 pages?

**Comment by kimadactyl** [comment]
that makes sense to me yeah!

**Comment by katjam** [comment]
So yes, persist the filter in the url between page navigations & set it whenever one of the buttons is pressed on any page (might cause the page to refresh)

**Comment by katjam** [comment]
I can release as it is now and do the enhancement over next few days. Are there any other "urgent" broken things preventing the release?

**Comment by kimadactyl** [comment]
i think #467 you could argue might be needed for release - it looks kinda bad if people are scrollign throgh multuple days with nothing on. depends how many `e` that is i think lol

**Comment by katjam** [comment]
> i think #467 you could argue might be needed for release - it looks kinda bad if people are scrollign throgh multuple days with nothing on. depends how many `e` that is i think lol

OK I can take a look and see how `e` it is. It's currently like that anyway so the only "worse" thing would be that Manchester has less events and so more likely for people to experience.
